services:
#    beneficiary.example:
#        class: BeneficiaryBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }