services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    admin.program.listener:
        class: AdminBundle\DoctrineListener\ProgramListener
        tags :
             - { name: doctrine.event_subscriber, connection: default } 

    AdminBundle\Service\:
        resource: '../../Service'
        autowire: true

    admin.form_field_manager:
        class: AdminBundle\Manager\SiteFormFieldSettingManager
        arguments: ['@doctrine.orm.entity_manager']