services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    admin.program.listener:
        class: AdminBundle\DoctrineListener\ProgramListener
        tags :
             - { name: doctrine.event_subscriber, connection: default } 

    AdminBundle\Service\:
        resource: '../../Service'
        autowire: true

    admin.form_field_manager:
        class: AdminBundle\Manager\SiteFormFieldSettingManager
        arguments: ['@doctrine.orm.entity_manager']

    admin.program:
        class: AdminBundle\Manager\ProgramManager
        arguments: ['@doctrine.orm.entity_manager', '@request_stack']

    admin.logo:
        class: AppBundle\Service\FileHandler\FileUploader
        arguments: ['%logo_path%']

    app.design_root:
        class: AppBundle\Service\FileHandler\DesignRoot
        arguments: ['%css_root%']

    admin.body_background:
        class: AppBundle\Service\FileHandler\FileUploader
        arguments: ['%background_path%']

    admin.role_rank:
        class: AdminBundle\Manager\ProgramRolesManager
        arguments: ['@doctrine.orm.entity_manager']

    admin.period_point:
        class: AdminBundle\Manager\PeriodPointManager
        arguments: ['@doctrine.orm.entity_manager']

    admin.point_attribution:
        class: AdminBundle\Manager\PointAttributionManager
        arguments: ['@doctrine.orm.entity_manager']

    AdminBundle\Manager\ProductPointAttributionManager:
        class: AdminBundle\Manager\ProductPointAttributionManager
        autowire: true
    

