imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AdminBundle/Resources/config/services.yml" }
    - { resource: "@BeneficiaryBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

    # "Administrateur" profile :
    # Parameters - Registration -Import : import file upload directory
    registration_import_file_upload_dir: '%kernel.project_dir%/web/registration/import'
    registration_model_dir: '%kernel.project_dir%/web/registration/model'
    result_setting_upload : '%kernel.project_dir%/web/result/upload'
    result_setting_model : '%kernel.project_dir%/web/result/model'
    registration_header_image_upload_dir: '%kernel.project_dir%/web/registration/upload/header'
    registration_header_image_location: 'registration/upload/header/'
    logo_path: 'images/logo'
    background_path: 'images/background'
    css_root: 'css/root'

    # Parameters - Registration - Import : Email texts
    be_contacted_email_subject: "Etre contacté"

    # Parameters - Content - Login portal : import file upload directory
    content_login_portal_slide_image_upload_dir: '%kernel.project_dir%/web/content/login_portal/slide'
    content_login_portal_slide_image_location: 'content/login_portal/slide/'

    # Parameters - Content - Home page : import file upload directory
    content_home_page_slide_image_upload_dir: '%kernel.project_dir%/web/content/home_page/slide'
    content_home_page_slide_image_location: 'content/home_page/slide/'

    # Parameters - Communication - Emailing - Templates : logo file upload directory
    emailing_template_logo_upload_dir: '%kernel.project_dir%/web/communication/emailing/template/logo'
    emailing_template_logo_location: 'communication/emailing/template/logo/'

    # Parameters - Communication - Emailing - Templates : image type content image file upload directory
    emailing_template_image_content_upload_dir: '%kernel.project_dir%/web/communication/emailing/template/image_content'
    emailing_template_image_content_location: 'communication/emailing/template/image_content/'

    # Parameters - Communication - Emailing - Templates : thumbnail
    emailing_template_thumbnail_dir: '%kernel.project_dir%/web/communication/emailing/template/thumbnail'
    emailing_template_thumbnail_location: 'communication/emailing/template/thumbnail/'

    # Application time zone
    app_time_zone: 'Europe/Paris'

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        registration_header_image_upload_dir: '%registration_header_image_upload_dir%'
        registration_header_image_location: '%registration_header_image_location%'
        content_login_portal_slide_image_location: '%content_login_portal_slide_image_location%'
        content_home_page_slide_image_location: '%content_home_page_slide_image_location%'
        locale: '%locale%'
        emailing_template_logo_location: '%emailing_template_logo_location%'
        emailing_template_image_content_location: '%emailing_template_image_content_location%'


# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    port: '%mailer_port%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# FOS User Bundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

# Liip Imageine Bundle configuration
liip_imagine:
    filter_sets:
        750_width_filter:
            filters:
                relative_resize:
                    widen: 750

        1920_width_filter:
            filters:
                upscale:                    
                    min: [1920, 346]

# Stof\DoctrineExtensionsBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true

krlove_async_service_call:
    console_path: 'bin/console'
    php_path: '%php_path%'

mailjet:
    api_key: "8b46705492737dcc775a869858066b64"
    secret_key: "7263741dd3d04301a7c3637adc14c31f"