<?php

namespace AdminBundle\Repository;

/**
 * ELearningHomeBannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ELearningHomeBannerRepository extends \Doctrine\ORM\EntityRepository
{

    public function getElearnigBanner($programID){

    }
}

