services:
    app.registration.confirm.listener:
        class: 'UserBundle\EventListener\RegistrationConfirmListener'
        arguments:
            - '@router'
            - '@service_container'
        tags:
            - { name: kernel.event_subscriber}

    user.authentication_success:
        class: UserBundle\EventListener\AuthenticationLoginSuccessListener
        arguments:
            - "@router"
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

    app.form.registration:
        class: UserBundle\Form\RegistrationType
        arguments:
            - "@service_container"
        tags:
            - { name: form.type, alias: app_user_registration }

        

    

    
